spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /resources/**
  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
#      - file:D://images/
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 20MB
  jmx:
    default-domain: devServer

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  page-size-zero: true

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8