export default {
	all: [{
		icon: 'article',
		name: '修改密码',
		bgColor: '#FF2851',
		url: '../passwordModify/passwordModify',
	}, {
		icon: 'article',
		name: '退出',
		bgColor: '#FF2851',
	}],
	user: [{
		icon: 'article',
		name: '公告',
		bgColor: '#FF2851',
		url: '../business/notice/user',
	},{
		icon: 'article',
		name: '预约管理',
		bgColor: '#FF2851',
		url: '../business/appointment/index/list',
	}],
	admin: [{
		icon: 'article',
		name: '公告管理',
		bgColor: '#FF2851',
		url: '../business/notice/list',
	}, {
		icon: 'article',
		name: '监管仓管理',
		bgColor: '#FF2851',
		url: '../business/warehouse/list',
	}, {
		icon: 'article',
		name: '监管仓人员',
		bgColor: '#FF2851',
		url: '../business/warehouseUser/list',
	}, {
		icon: 'article',
		name: '设备管理',
		bgColor: '#FF2851',
		url: '../business/device/list',
	}, {
		icon: 'article',
		name: '废物处理',
		bgColor: '#FF2851',
		url: '../business/wasteDisposal/list',
	}, {
		icon: 'article',
		name: '消毒液管理',
		bgColor: '#FF2851',
		url: '../business/disinfectant/list',
	}, {
		icon: 'article',
		name: '环境消杀记录',
		bgColor: '#FF2851',
		url: '../business/disinfectionRecord/list',
	}, {
		icon: 'article',
		name: '预约管理',
		bgColor: '#FF2851',
		url: '../business/notice/list',
	}, {
		icon: 'article',
		name: '入仓管理',
		bgColor: '#FF2851',
		url: '../business/appointment/warehousing/list',
	}, {
		icon: 'article',
		name: '出仓管理',
		bgColor: '#FF2851',
		url: '../business/appointment/warehoused/list',
	}],
	system: [{
		icon: 'article',
		name: '用户管理',
		bgColor: '#FF2851',
		url: '../user/list',
	}]
}
